In [214]:
import pandas as pd
from io import BytesIO
import requests
import random

In [215]:
def fetch_data(url, skiprows=0):
    r = requests.get(url)
    data = r.content

    return pd.read_csv(BytesIO(data), index_col=0, skiprows=skiprows)

catalog = fetch_data("https://docs.google.com/spreadsheets/d/1JyGlqmLg9k7UubOw-V_CC8McRZxn2PtknvsrMIxvLGk/export?gid=0&format=csv", 2)
data_interp_catalog = fetch_data("https://docs.google.com/spreadsheets/d/1JyGlqmLg9k7UubOw-V_CC8McRZxn2PtknvsrMIxvLGk/export?gid=1340046923&format=csv", 0)

completed_sets = fetch_data("https://docs.google.com/spreadsheets/d/1JyGlqmLg9k7UubOw-V_CC8McRZxn2PtknvsrMIxvLGk/export?gid=1791033131&format=csv")
completed_suppl = fetch_data("https://docs.google.com/spreadsheets/d/1JyGlqmLg9k7UubOw-V_CC8McRZxn2PtknvsrMIxvLGk/export?gid=399306386&format=csv")
gen_sets = fetch_data("https://docs.google.com/spreadsheets/d/1JyGlqmLg9k7UubOw-V_CC8McRZxn2PtknvsrMIxvLGk/export?gid=998252116&format=csv")

In [216]:
categories = catalog.keys()[7:]
repl_nan = { i : False for i in catalog.keys()[3:]}
repl_checked = { i : 'x' for i in catalog.keys()[3:]}

scrubbed_cat = catalog.fillna(value=repl_nan).replace(repl_checked, True)
#scrubbed_cat.head()
#categories

In [217]:
categorical_cols = scrubbed_cat.columns[3:7]
skillset_cols = scrubbed_cat.columns[7:-4]
misc_cols = scrubbed_cat.columns[-4:]
#categorical_cols
#skillset_cols
#misc_cols

In [218]:
incomplete_sets = gen_sets[gen_sets['Test Taken'] != True]
incomplete_sets

           Set Id  Local Id Test Taken
Global Id
251             4     12.03        NaN
55              4      7.06        NaN
780             4     29.11        NaN
133             4      9.21        NaN
523             4     20.17        NaN
761             4     28.16        NaN
586             4     22.07        NaN
606             4     22.27        NaN
283             4     12.35        NaN
439             4     17.07        NaN
421             4     16.17        NaN
408             4     16.04        NaN
390             4     15.25        NaN
67              4      7.18        NaN
7               4     24.07        NaN
8               4     24.08        NaN
6               4     24.06        NaN
608             4     22.29        NaN
788             4     30.01        NaN
705             4     27.02        NaN
522             5     20.16        NaN
724             5     27.21        NaN
530             5     20.24        NaN
712             5     27.09        NaN
732             5     27.29        NaN
369             5     15.04        NaN
813             5     30.26        NaN
355             5     14.20        NaN
486             5     18.29        NaN
616             5     23.06        NaN
...           ...       ...        ...
185            21     10.32        NaN
327            21     13.25        NaN
167            21     10.14        NaN
630            21     23.20        NaN
605            21     22.26        NaN
343            21     14.08        NaN
546            21     21.04        NaN
796            21     30.09        NaN
484            21     18.27        NaN
357            21     14.22        NaN
547            22     21.05        NaN
229            22     11.19        NaN
332            22     13.30        NaN
740            22     27.37        NaN
735            22     27.32        NaN
813            22     30.26        NaN
288            22     12.40        NaN
303            22     13.01        NaN
786            22     29.17        NaN
796            22     30.09        NaN
630            22     23.20        NaN
207            22     10.54        NaN
483            22     18.26        NaN
484            22     18.27        NaN
139            22      9.27        NaN
623            22     23.13        NaN
192            22     10.39        NaN
824            22     30.37        NaN
119            22      9.07        NaN
205            22     10.52        NaN

[380 rows x 3 columns]

In [219]:
completed_full = pd.concat([completed_sets, completed_suppl], ignore_index=False, sort=False).drop_duplicates()
completed_full

           Set Id  Local Id Completed Correct Date Unnamed: 4
Global Id
807           1.0     30.20      True    True  NaN        NaN
722           1.0     27.19      True    True  NaN        NaN
696           1.0     26.18      True    True  NaN        NaN
675           1.0     25.19     False    True  NaN        NaN
663           1.0     25.07      True    True  NaN        NaN
612           1.0     23.02      True    True  NaN        NaN
583           1.0     22.04      True    True  NaN        NaN
525           1.0     20.19      True    True  NaN        NaN
489           1.0     19.03      True   False  NaN        NaN
457           1.0     17.25      True    True  NaN        NaN
438           1.0     17.06      True    True  NaN        NaN
409           1.0     16.05      True    True  NaN        NaN
352           1.0     14.17      True    True  NaN        NaN
321           1.0     13.19      True   False  NaN        NaN
310           1.0     13.08      True    True  NaN        NaN
253           1.0     12.05      True    True  NaN        NaN
173           1.0     10.20      True    True  NaN        NaN
163           1.0     10.10      True    True  NaN        NaN
126           1.0      9.14      True    True  NaN        NaN
103           1.0      8.26      True    True  NaN        NaN
777           2.0     29.18      True    True  NaN        NaN
769           2.0     29.08      True    True  NaN        NaN
672           2.0     28.24      True    True  NaN        NaN
601           2.0     28.11      True    True  NaN        NaN
601           2.0     26.05      True    True  NaN        NaN
568           2.0     25.16      True    True  NaN        NaN
2             2.0     24.02      True    True  NaN        NaN
568           2.0     22.22      True   False  NaN        NaN
554           2.0     21.26      True    True  NaN        NaN
511           2.0     21.12      True    True  NaN        NaN
...           ...       ...       ...     ...  ...        ...
632           NaN     23.22       NaN   False  NaN        NaN
634           NaN     23.24       NaN    True  NaN        NaN
396           NaN     15.31       NaN    True  NaN        NaN
376           NaN     15.11       NaN    True  NaN        NaN
643           NaN     23.33       NaN    True  NaN        NaN
80            NaN      8.03       NaN    True  NaN        NaN
787           NaN     29.18       NaN    True  NaN        NaN
695           NaN     26.17       NaN   False  NaN        NaN
697           NaN     26.19       NaN    True  NaN        NaN
377           NaN     15.12       NaN    True  NaN        NaN
477           NaN     18.20       NaN    True  NaN        NaN
770           NaN     29.01       NaN    True  NaN        NaN
337           NaN     14.02       NaN    True  NaN        NaN
782           NaN     29.13       NaN    True  NaN        NaN
526           NaN     20.20       NaN    True  NaN        NaN
132           NaN      9.20       NaN    True  NaN       hard
351           NaN     14.16       NaN    True  NaN       hard
531           NaN     20.25       NaN    True  NaN        NaN
654           NaN     23.44       NaN    True  NaN       hard
120           NaN      9.08       NaN    True  NaN        NaN
144           NaN      9.32       NaN   False  NaN        NaN
356           NaN     14.21       NaN    True  NaN        NaN
655           NaN     23.45       NaN     NaN  NaN        NaN
465           NaN     18.08       NaN     NaN  NaN        NaN
145           NaN      9.33       NaN     NaN  NaN        NaN
719           NaN     27.16       NaN     NaN  NaN        NaN
528           NaN     20.22       NaN     NaN  NaN        NaN
346           NaN     14.11       NaN     NaN  NaN        NaN
527           NaN     20.21       NaN     NaN  NaN        NaN
742           NaN     27.39       NaN     NaN  NaN        NaN

[156 rows x 6 columns]

In [220]:
used_qs = pd.concat([completed_full, incomplete_sets], ignore_index=False, sort=False)
used_qs

           Set Id  Local Id Completed Correct Date Unnamed: 4 Test Taken
Global Id
807           1.0     30.20      True    True  NaN        NaN        NaN
722           1.0     27.19      True    True  NaN        NaN        NaN
696           1.0     26.18      True    True  NaN        NaN        NaN
675           1.0     25.19     False    True  NaN        NaN        NaN
663           1.0     25.07      True    True  NaN        NaN        NaN
612           1.0     23.02      True    True  NaN        NaN        NaN
583           1.0     22.04      True    True  NaN        NaN        NaN
525           1.0     20.19      True    True  NaN        NaN        NaN
489           1.0     19.03      True   False  NaN        NaN        NaN
457           1.0     17.25      True    True  NaN        NaN        NaN
438           1.0     17.06      True    True  NaN        NaN        NaN
409           1.0     16.05      True    True  NaN        NaN        NaN
352           1.0     14.17      True    True  NaN        NaN        NaN
321           1.0     13.19      True   False  NaN        NaN        NaN
310           1.0     13.08      True    True  NaN        NaN        NaN
253           1.0     12.05      True    True  NaN        NaN        NaN
173           1.0     10.20      True    True  NaN        NaN        NaN
163           1.0     10.10      True    True  NaN        NaN        NaN
126           1.0      9.14      True    True  NaN        NaN        NaN
103           1.0      8.26      True    True  NaN        NaN        NaN
777           2.0     29.18      True    True  NaN        NaN        NaN
769           2.0     29.08      True    True  NaN        NaN        NaN
672           2.0     28.24      True    True  NaN        NaN        NaN
601           2.0     28.11      True    True  NaN        NaN        NaN
601           2.0     26.05      True    True  NaN        NaN        NaN
568           2.0     25.16      True    True  NaN        NaN        NaN
2             2.0     24.02      True    True  NaN        NaN        NaN
568           2.0     22.22      True   False  NaN        NaN        NaN
554           2.0     21.26      True    True  NaN        NaN        NaN
511           2.0     21.12      True    True  NaN        NaN        NaN
...           ...       ...       ...     ...  ...        ...        ...
185          21.0     10.32       NaN     NaN  NaN        NaN        NaN
327          21.0     13.25       NaN     NaN  NaN        NaN        NaN
167          21.0     10.14       NaN     NaN  NaN        NaN        NaN
630          21.0     23.20       NaN     NaN  NaN        NaN        NaN
605          21.0     22.26       NaN     NaN  NaN        NaN        NaN
343          21.0     14.08       NaN     NaN  NaN        NaN        NaN
546          21.0     21.04       NaN     NaN  NaN        NaN        NaN
796          21.0     30.09       NaN     NaN  NaN        NaN        NaN
484          21.0     18.27       NaN     NaN  NaN        NaN        NaN
357          21.0     14.22       NaN     NaN  NaN        NaN        NaN
547          22.0     21.05       NaN     NaN  NaN        NaN        NaN
229          22.0     11.19       NaN     NaN  NaN        NaN        NaN
332          22.0     13.30       NaN     NaN  NaN        NaN        NaN
740          22.0     27.37       NaN     NaN  NaN        NaN        NaN
735          22.0     27.32       NaN     NaN  NaN        NaN        NaN
813          22.0     30.26       NaN     NaN  NaN        NaN        NaN
288          22.0     12.40       NaN     NaN  NaN        NaN        NaN
303          22.0     13.01       NaN     NaN  NaN        NaN        NaN
786          22.0     29.17       NaN     NaN  NaN        NaN        NaN
796          22.0     30.09       NaN     NaN  NaN        NaN        NaN
630          22.0     23.20       NaN     NaN  NaN        NaN        NaN
207          22.0     10.54       NaN     NaN  NaN        NaN        NaN
483          22.0     18.26       NaN     NaN  NaN        NaN        NaN
484          22.0     18.27       NaN     NaN  NaN        NaN        NaN
139          22.0      9.27       NaN     NaN  NaN        NaN        NaN
623          22.0     23.13       NaN     NaN  NaN        NaN        NaN
192          22.0     10.39       NaN     NaN  NaN        NaN        NaN
824          22.0     30.37       NaN     NaN  NaN        NaN        NaN
119          22.0      9.07       NaN     NaN  NaN        NaN        NaN
205          22.0     10.52       NaN     NaN  NaN        NaN        NaN

[536 rows x 7 columns]

In [221]:
j = scrubbed_cat.join(used_qs, how='left', lsuffix='_left', rsuffix='_right', sort=False)
remaining_qs = j[j['Local Id_right'].isna()]
remaining_qs

,Local Id_left,Source,Type,AR,ALG,DA,GEO,ARG,FAD,PCT,...,VC,AQ,DI,Set Id,Local Id_right,Completed,Correct,Date,Unnamed: 4,Test Taken
Global Id,,,,,,,,,,,,,,,,,,,,,
50,7.01,M,QC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,7.02,M,QC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,7.04,M,NE,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,7.05,M,QC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,7.07,M,QC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,7.13,M,QC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,7.14,M,MC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,7.19,M,NE,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,7.21,M,MC,True,True,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,7.22,M,NE,True,True,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,7.26,M,MC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,7.27,M,MC,True,False,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,7.28,M,MA,True,True,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,8.01,M,NE,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,8.06,M,MC,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,8.07,M,QC,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,8.09,M,QC,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,8.10,M,MC,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,8.12,M,NE,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,8.13,M,NE,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,8.16,M,QC,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,8.17,M,QC,True,True,False,False,True,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,8.18,M,QC,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,8.21,M,QC,True,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,8.22,M,MA,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,8.23,M,QC,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,8.24,M,MC,True,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,8.30,M,NE,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,8.31,M,NE,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,8.32,M,NE,False,True,False,False,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,28.17,M,QC,False,False,False,True,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,29.05,M,MC,False,False,False,True,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,29.07,M,MC,False,False,False,True,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
778,29.09,M,MC,False,False,False,True,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783,29.14,M,MC,False,False,False,True,False,False,False,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789,30.02,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,30.04,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792,30.05,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
793,30.06,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,30.10,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,30.12,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,30.13,M,MA,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
801,30.14,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
802,30.15,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
803,30.16,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
805,30.18,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
806,30.19,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,30.21,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810,30.23,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
811,30.24,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
812,30.25,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
814,30.27,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815,30.28,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
819,30.32,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
820,30.33,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,30.34,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
822,30.35,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
823,30.36,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
827,30.40,M,MC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
828,30.41,M,QC,False,False,False,False,False,False,False,...,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [222]:
def sample_questions(remaining_qs, count_per_key):
    used = set()
    samples = {}
    for k in count_per_key:
        filtered = remaining_qs[remaining_qs[k] == True]
        sample = filtered.sample(count_per_key[k])['Local Id_left']
        rows = list(tuple(zip(sample.index, sample)))
        
        to_remove = []
        to_add = []
        for row in rows:
            if row[0] in used:
                to_remove.append(row)
                
                i = 0
                while i < 3:
                    resampled = filtered.sample(1)['Local Id_left']
                    r = resampled.iloc[0].index
                    if r not in used:
                        to_add.append((r.index, r['Local Id_left']))
        
        for r in to_remove:
            rows.remove(r)
        rows += to_add
        
        samples[k] = sample
        for r in rows:
            used.add(r[0])
            
    return samples

def flatten_and_shuffle(samples):
    qs = []
    for v in samples.values():
        qs += list(tuple(zip(v.index, v)))
    random.shuffle(qs)
    
    return qs

In [228]:
sample_sizes = {
    'TRI': 4,
    'EAF': 4,
    'PROB': 4,
    'PCT': 4,
    'WP': 4,
    'VC': 1,
    'ARG': 3,
    'DST': 2,
    '2WP': 2,
    'CG': 1,
    'AQ': 1
}
sample_qs = sample_questions(remaining_qs, sample_sizes)
shuffled = flatten_and_shuffle(sample_qs)
shuffled

[(500, 19.14),
 (593, 22.14),
 (743, 27.4),
 (269, 12.21),
 (76, 7.27),
 (738, 27.35),
 (302, 12.54),
 (93, 8.16),
 (762, 28.17),
 (638, 23.28),
 (107, 8.3),
 (709, 27.06),
 (414, 16.1),
 (56, 7.07),
 (101, 8.24),
 (260, 12.12),
 (455, 17.23),
 (417, 16.13),
 (51, 7.02),
 (639, 23.29),
 (108, 8.31),
 (607, 22.28),
 (725, 27.22),
 (413, 16.09),
 (452, 17.2),
 (644, 23.34),
 (627, 23.17),
 (429, 16.25),
 (819, 30.32),
 (280, 12.32)]

In [229]:
any([x[0] for x in shuffled if x[0] in used_qs.index])

False

In [230]:
df = pd.DataFrame(shuffled, columns =['Global Id', 'Local Id'])
df.to_csv(r'C:\Users\bille\Documents\git\gre_analysis\sup_gen.csv', index=False)